# <center>EXPERIMENT 2<center>NUMERICAL PYTHON (NUMPY)

In [128]:
#The most import part, which is to call the library
import numpy as np

# NORMALIZATION PROBLEM:

In [131]:
#Create the random 5 x 5 ndarray
X = np.random.random((5,5))

#The computation for normalization ((num - mean) / standard deviation))
X = ((X - X.mean())/(X.std()))

#Output the values to check
X

array([[ 0.73916094,  1.16988716,  1.34860592, -1.45584647,  1.52508211],
       [ 0.48025981,  1.20900152, -1.00998879, -1.42833994,  0.3216694 ],
       [-0.19581744,  0.28878346,  1.60960393, -0.9003887 ,  1.10987687],
       [-0.74545139,  1.00703329, -1.00525855, -0.79957904,  0.33099161],
       [-1.43118329, -0.87410098, -0.57406318, -0.84960709,  0.12966881]])

In [133]:
#As specified save the normalized values as X_Normalize.npy
np.save('X_Normalize.npy',X)

In [135]:
#Check if the stored values are the same 
np.load('X_Normalize.npy')

array([[ 0.73916094,  1.16988716,  1.34860592, -1.45584647,  1.52508211],
       [ 0.48025981,  1.20900152, -1.00998879, -1.42833994,  0.3216694 ],
       [-0.19581744,  0.28878346,  1.60960393, -0.9003887 ,  1.10987687],
       [-0.74545139,  1.00703329, -1.00525855, -0.79957904,  0.33099161],
       [-1.43118329, -0.87410098, -0.57406318, -0.84960709,  0.12966881]])

# DIVISIBLE BY 3 PROBLEM:

In [138]:
#First create the specified 10 x 10 ndarray

#First create an array with the first 100 integers (1 - 100)
firstInt = np.arange(1, 101)

#Second square the values (1 - 10000)
squared = firstInt ** 2

#Third turn the array into a 10 x 10
A = squared.reshape(10, 10)

#Select/sort the elements that fit the parameters (all elements that are divisible by 3)
worthy = A[A%3==0]

#Output for debugging 
worthy

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [140]:
#As specified save the numbers divisible by three to div_by_3.npy
np.save('div_by_3.npy',worthy)

In [142]:
#Check if the stored values are the same 
np.load('div_by_3.npy')

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])